### ISSUE TITLE
Copy SteamID from players table does not work

### ISSUE THREAD

**Issue by Bazimek** [alexander171294/RustMon#10]
When I click on copy steamid it won't copy it.

**Comment by alexander171294** [comment]
Work in progress

**Comment by alexander171294** [comment]
what browser are you using?

**Comment by Bazimek** [comment]
Chrome, Edge

**Comment by alexander171294** [comment]
I can't reproduce this, i think this works in latest version.

**Comment by Bazimek** [comment]
Does not work for me, maybe some Chrome plugin. I will try it.

**Comment by Bazimek** [comment]
Not working :(

**Comment by alexander171294** [comment]
I can't reproduce it, you may have a public endpoint with your version uploaded? to try.

Thanks for the issue.

**Comment by alexander171294** [comment]
The best i can do, is when you using host without ssl, a popup top-right appears saying can't copy and give you the id for manually copy.

**Comment by alexander171294** [comment]
you can see it here: http://rustmon.tandilserver.com/#/connector
