### ISSUE TITLE
Implement a BetterChat plugin?

### ISSUE THREAD

**Issue by Bazimek** [alexander171294/RustMon#13]
Hello can you somehow implement betterchat plugin to be more beautiful in chat window than now?

**Comment by alexander171294** [comment]
IDK what is betterchat, I use vanilla rust servers.

please send me an example.

**Comment by Bazimek** [comment]
https://umod.org/plugins/better-chat this plugin and what it will do in the chat window of Rust Monitor is this:

![image](https://user-images.githubusercontent.com/17622398/113913452-a4e4f600-97dc-11eb-8e93-73990f3debf1.png)

Like there is double name ... -> Name Name: Message
if player got a title it is like
Name Title Name: Message

**Comment by alexander171294** [comment]
I can't support external plugins because isn't standard and depending of dev implementation.

If you want, you can edit your copy and test it.

Srry :(

**Comment by Bazimek** [comment]
Not even in configuration have something like BetterChat plugin checkbox and then set different settings? :( I know the RustAdmin have something like this.

**Comment by alexander171294** [comment]
RustAdmin do that with a plugin? :O
