### ISSUE TITLE
Possible for autofill the server ip, port, password?

### ISSUE THREAD

**Issue by Bazimek** [alexander171294/RustMon#15]
Hey will it be possible to autofill the server ip, port, rcon password for connect via www adress? Something like:

http://rustmonitor?ip=X.X.X.X?port=280XX?pass=XXXX

??? Or how can I change this
<input type="text" placeholder="server ip" [(ngModel)]="serverIP" (keypress)="kpConn($event)"/>

to something like this?
<input type="text" value="X.X.X.X" placeholder="server ip" [(ngModel)]="serverIP" (keypress)="kpConn($event)"/>

**Comment by alexander171294** [comment]
In the last version you can do this:

http://rustmonitor/#/connector;server=127.0.0.1;rport=28016;password=12345678
