### ISSUE TITLE
Restart command how to add another new PromptData?

### ISSUE THREAD

**Issue by Bazimek** [alexander171294/RustMon#24]
Hello, I am trying to add another new PromptData for restart button, because the command can be like restart <time> <reason>, but I am not a programmer do to this. Can you add it or tell me how can I add second prompot for reason?

**Comment by alexander171294** [comment]
I don't understand why you want to add new prompt.

Please explain me the use case.

**Comment by Bazimek** [comment]
Because you can't post that restart with a reason. You are doing only restart <time>. But you can do restart <time> <reason>

**Comment by alexander171294** [comment]
oh, okay, I can add that feature.

**Comment by Bazimek** [comment]
Thank you, but it is really not a priority one. It is only just small thing. You can add it after some big one update will be there.

**Comment by alexander171294** [comment]
This was added.
I'm starting local rust server to try the other issue related to chat modification.

I added also VAC Warning with red icon in user list, and private profile warning with yellow icon in user list, and if you click in the user list, now it's opened a popup with steam user data. (As vac days, etc.)

**Comment by Bazimek** [comment]
Oh that is really nice! I will be using that for sure! Great idea. Thank you. Can't wait if you can fix the chat with better chat addon.
