### ISSUE TITLE
Can't run it online

### ISSUE THREAD

**Issue by Bazimek** [alexander171294/RustMon#4]
Hello how can I run this awesome tool online? Not only in local on localhost.

**Comment by alexander171294** [comment]
Hi!, right now I haven't an instance of rust server to check this, but in the future I check it.
Probably the dev team of rust changed anything.

**Comment by Bazimek** [comment]
Closed. Found it out. :)

**Comment by alexander171294** [comment]
In first place, you can run ng build --prod and put the dist folder in a web hosting (apache, nginx, any web hosting, including shared hosts).

But additionally I put a docker file for run an instance, and I created an endpoint.

docker run -p 8086:80 -itd alexander171294/rustmon:latest

http://irc.tandilserver.com:8086/

**Comment by Bazimek** [comment]
Wait what?! I can run this on classic web hosting? That is awesome! How? When i use ng build --prod I just get some errors.
![Výstřižek](https://user-images.githubusercontent.com/17622398/88422201-254bfe00-cdea-11ea-9dca-e0179088a02c.PNG)

**Comment by alexander171294** [comment]
Please pull for get this commit: https://github.com/alexander171294/RustMon/commit/6ac9ce8eede1110ade3e345359d82335ea452df6, that fix your problem.

When you build, this generate a dist/rustmon folder with plain html+javascript content that you can upload with ftp to a classic webhost (shared hosting).
