### ISSUE TITLE
Time in chat is incorrect and frozen

### ISSUE THREAD

**Issue by Bazimek** [alexander171294/RustMon#5]
19/1/70 12:10 in every message in chat

**Comment by alexander171294** [comment]
Hi!, right now I haven't an instance of rust server to check this, but in the future I check it.
Probably the dev team of rust changed anything.

**Comment by Bazimek** [comment]
![RustMonitor timestamp](https://user-images.githubusercontent.com/17622398/88214826-1125c680-cc5b-11ea-91a7-e23826e82d47.PNG)

**Comment by Bazimek** [comment]
Can you check that? And where can I post the feature request?

**Comment by Bazimek** [comment]
I'm not an programmer, but I change this:
<span class="time">[{{message.Time | date:'d/M/yyyy, h:mm'}}]</span>

to this:
<span class="time">[{{message.Time * 1000 | date:'d/M/yyyy, HH:mm'}}]</span> (for 24h time)

And it is working!

**Comment by alexander171294** [comment]
Excellent!, thanks.
