### ISSUE TITLE
Is this completelay abandoned?

### ISSUE THREAD

**Issue by GameAreaCZ** [alexander171294/RustMon#56]
The status do not work at all.

**Comment by GenkiPL** [comment]
Rly? so sad I love app's like this.

**Comment by alexander171294** [comment]
Hi, what do you mean with "status do not work at all"?, can you put a photo or an example?

thanks

**Comment by GenkiPL** [comment]
Hello

I think the project is quite abandoned - the software does not work with the new version of rust.

After a great search for good software, I decided to buy "My Rust Server"
See how nice it is!
A cool option is to install plugins from within the program!
Plus it has a built-in plugin configuration editor with automatic refresh!
works well under Windows - Until now I used LGSM on ubuntu but I have colleagues who do not understand the goodness of Linux :)

Anyway, I highly recommend "My Rust server", which has super support on Discord :)


[cid:65b83201-26f2-4c30-8fb8-5be9e8953e13]


best regards!
Genki



________________________________
Od: Alexander ***@***.***>
Wysłane: sobota, 18 maja 2024 22:52
Do: alexander171294/RustMon ***@***.***>
DW: GenkiPL ***@***.***>; Comment ***@***.***>
Temat: Re: [alexander171294/RustMon] Is this completelay abandoned? (Issue #56)


Hi, what do you mean with "status do not work at all"?, can you put a photo or an example?

thanks
