### ISSUE TITLE
Console command send with enter does not work

### ISSUE THREAD

**Issue by Bazimek** [alexander171294/RustMon#8]
Hello, the console command send with enter does not work. Can you fix it please?

**Comment by Bazimek** [comment]
Bump

**Comment by alexander171294** [comment]
done, if you want other new functions, please create an issue.

**Comment by Bazimek** [comment]
Oh nice! Thank you! Do you have some tutorial how to update it without losing my added stuff? I added like FPS showing, entity show, button for writecfg etc. But im so excited for this issue fixed.

**Comment by alexander171294** [comment]
can you share me your project with the changes in order to implement in my project?, if you would like to contribute.

In any case, you can add this changes https://github.com/alexander171294/RustMon/commit/6105f30825166be6b416f4d71306192674a09aa7
to your project.

**Comment by Bazimek** [comment]
Thank you very much for your help. I have changed this stuff:

1. Added EntityCount to the top
2. Added FPS to the top
3. Repair time in chat (was 1970)
4. Added button for writecfg command
5. Added button for o.version check command

These are just my tries and I don't think so everyone like them. It is not much, but I am not a programmer so for me it was a lot of work. :-D If you want I can ofcourse share the code with you, but I think for you it is like one minute of work.
![rustmonitor](https://user-images.githubusercontent.com/17622398/111060111-ea8ef700-849a-11eb-922f-479f524022b1.jpg)

**Comment by Bazimek** [comment]
One more thing. Where I can add a suggestion for a feature? That is a pull request here? And thank you very much for this update. Sending commands with enter is so much smoother, relaxing than clickin on the button EXEC and SEND

**Comment by alexander171294** [comment]
I will work with this features and copy steamid feature.

If you want to request a new feature, please open an issue with label "enhancement"

Thanks!

**Comment by alexander171294** [comment]
Hi! Bazimek, you can see the last changes here: 

https://github.com/alexander171294/RustMon/releases/tag/0.0.2

I added Entity count, Fps count, fixed time, adding full screen for configure your server info and writecfg button, I added a set of preloaded commands as o.version, time, populations, infos and calls.

I added a link to full command list in console panel, and context-menu (right click) in chat. And I added queue and skipqueue command (but I can't test it because I don't have a server).

And fix another smallest issues, please you can try to update (clone in anothe folder and test it).

If you have any question or comment, please write it.

**Comment by Bazimek** [comment]
Hello, very nice update. I love it! Only what I don't like personally is the AM/PM time. I like the 24h time format. So I will try change that for myself. But it will be so good to have like panel-configuration menu for things like that if this is possible. 

I added a link to full command list in console panel

What is this exactly? When I right click in the console panel nothing happening (only normally windows menu).

**Comment by alexander171294** [comment]
AM/PM? I don't know where is it, in the screenshots you can see the chat time format is in 24hs mode (i think).

The command list is in top of console panel, floating right to the title "Console" have an icon "(?)" this open new window with 3rd party page of full command list and details.

Thanks, I will update the endpoint rustmon.tandilserver.com soon!
